name: Application deployment

on:
  push:
    branches:
      - master
      - beta
  workflow_dispatch:
    inputs:
      deploy_type:
        description: 'Type of deployment'
        required: true
        default: 'alpha'

jobs:
  initialize:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: Get VERSION_CODE
        id: commit-count
        run: |
          let nb=$(git rev-list HEAD --count)+500
          echo "COUNT=$nb" >> $GITHUB_OUTPUT
        
      - name: Get VERSION_NUMBER
        id: version-number
        run: |
          ver="$(git describe --tags --dirty)"
          echo "VERSION=${ver}" >> $GITHUB_OUTPUT
          ios_ver="$(echo $ver | cut -d'-' -f1)"
          echo "IOS_VERSION=${ios_ver}" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Get deploy type
        id: deploy-type
        run: |
          if [ "${{ github.ref }}" == "refs/heads/master" ]; then
            echo "TYPE=prod" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref }}" == "refs/heads/beta" ]; then
            echo "TYPE=beta" >> $GITHUB_OUTPUT
          else
            echo "TYPE=unknown" >> $GITHUB_OUTPUT
          fi
          
    outputs:
      VERSION_CODE: ${{ steps.commit-count.outputs.COUNT }}
      VERSION_NUMBER: ${{ steps.version-number.outputs.VERSION }}
      IOS_VERSION: ${{ steps.version-number.outputs.IOS_VERSION }}
      DEPLOY_TYPE: ${{ steps.deploy-type.outputs.TYPE }}


  deploy_android:
    if: ${{ inputs.deploy_type != 'alpha' }}
    needs: initialize
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Java
        run: |
          brew tap AdoptOpenJDK/openjdk
          brew install --cask adoptopenjdk15

          echo "JAVA_HOME=$(/usr/libexec/java_home -v 15)" >> $GITHUB_ENV
          echo ${{ env.JAVA_HOME }}
          java -version

      - name: Setup Android CLI
        run: |
          brew install --cask android-commandlinetools
          sdkmanager --update
          set +o pipefail

          yes | sdkmanager --licenses
          yes | sdkmanager --install "platform-tools"
          yes | sdkmanager --install "build-tools;33.0.1"
          yes | sdkmanager --install "platforms;android-33"

          sdkmanager --list_installed
          set -o pipefail

      - name: Setup Android Builder
        run: |
          echo "ANDROID_HOME=$(brew --prefix)/share/android-commandlinetools" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$(brew --prefix)/share/android-commandlinetools" >> $GITHUB_ENV
          echo "APP_VERSION_CODE=${{ needs.initialize.outputs.VERSION_CODE  }}" >> $GITHUB_ENV
          echo "APP_VERSION_NUMBER=${{ needs.initialize.outputs.VERSION_NUMBER }}" >> $GITHUB_ENV
          chmod +x ./android/gradlew;

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Setup dependencies
        run: |
          npm i -g @ionic/cli
          npm i --prefer-offline --no-audit

      - name: Update release canal
        uses: maxgfr/github-change-json@main
        with:
          path: "package.json"
          key: "canal"
          value: ${{ needs.initialize.outputs.DEPLOY_TYPE }}

      - name: Update version number
        uses: maxgfr/github-change-json@main
        with:
          path: "package.json"
          key: "version"
          value: ${{ needs.initialize.outputs.VERSION_NUMBER }}

      - name: Ionic Capacitor Sync
        run: |
          ionic capacitor sync android --prod
     
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true

      - name: Cache bundle dependencies
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-

      - name: Decrypt Android keys
        run: sh ./.github/scripts/decrypt_android_keys.sh
        env:
          KEYS_SECRET_PASSPHRASE: ${{ secrets.KEYS_SECRET_PASSPHRASE }}  

      - name: Export Data to Fastlane
        run: |
          echo "KEY_STORE=$GITHUB_WORKSPACE/android/fastlane/logi12-prnplus.jks" >> $GITHUB_ENV
          echo "KEY_STORE_PASSWORD=${{ secrets.KEY_STORE_PASSWORD}}" >> $GITHUB_ENV
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV
          echo "PLAY_CREDENTIALS_JSON=$GITHUB_WORKSPACE/android/fastlane/play_store.json" >> $GITHUB_ENV
          echo "GRADLE_FILE=$GITHUB_WORKSPACE/android/app/build.gradle" >> $GITHUB_ENV

      - name: Download bundle dependencies
        run: |
          gem install bundler:2.0.2
          bundle config path vendor/bundle
          bundle install
          bundle exec gem install "fastlane-plugin-versioning_android"
        working-directory: android/fastlane

      - name: Build and deploy
        run: |
          echo "LC_ALL=fr_FR.UTF-8" >> $GITHUB_ENV
          echo "LANG=fr_FR.UTF-8" >> $GITHUB_ENV
          bundle exec fastlane ${{ needs.initialize.outputs.DEPLOY_TYPE }}
        working-directory: android/fastlane

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Android App - ${{ needs.initialize.outputs.VERSION_NUMBER }} - APK
          path: ${{ env.APK_LOCATION }}
          retention-days: 3


  deploy_ios:
    if: ${{ inputs.deploy_type != 'alpha' }}
    needs: initialize
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Init XCode SDK
        run: xcodebuild -sdk -version

      - name: Setup dependencies
        run: |
          npm i -g @ionic/cli
          npm i --prefer-offline --no-audit

      - name: Update release canal
        uses: maxgfr/github-change-json@main
        with:
          path: "package.json"
          key: "canal"
          value: ${{ needs.initialize.outputs.DEPLOY_TYPE }}

      - name: Update version number
        uses: maxgfr/github-change-json@main
        with:
          path: "package.json"
          key: "version"
          value: ${{ needs.initialize.outputs.VERSION_NUMBER }}

      - name: Ionic Capacitor Sync
        run: |
          ionic capacitor sync ios --prod
     
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true

      - name: Cache bundle dependencies
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-

      - name: Setup SSH Keys and known_hosts for Fastlane Match
        run: |
            SSH_PATH="$HOME/.ssh"
            mkdir -p "$SSH_PATH"
            touch "$SSH_PATH/known_hosts"    
            echo "$PRIVATE_KEY" > "$SSH_PATH/id_rsa"    
            chmod 700 "$SSH_PATH"
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            chmod 600 "$SSH_PATH/known_hosts"
            chmod 600 "$SSH_PATH/id_rsa"    
            eval $(ssh-agent)
            ssh-add "$SSH_PATH/id_rsa"
        env:
          PRIVATE_KEY: ${{ secrets.SSH_KEY }}

      - name: Decrypt iOS keys
        run: sh ./.github/scripts/decrypt_ios_keys.sh
        env:
          KEYS_SECRET_PASSPHRASE: ${{ secrets.KEYS_SECRET_PASSPHRASE }}  

      - name: Export Data to Fastlane
        run: |
          echo "APP_STORE_API_KEY_ID=${{ secrets.APP_STORE_API_KEY_ID }}" >> $GITHUB_ENV
          echo "APP_STORE_API_KEY_ISSUER_ID=${{ secrets.APP_STORE_API_KEY_ISSUER_ID }}" >> $GITHUB_ENV
          echo "APP_STORE_API_KEY=${{ secrets.APP_STORE_API_KEY }}" >> $GITHUB_ENV
          echo "CERTIFICATE_STORE_GITHUB_URL=${{ secrets.CERTIFICATE_STORE_GITHUB_URL }}" >> $GITHUB_ENV
          echo "MATCH_PASSWORD=${{ secrets.MATCH_PASSWORD }}" >> $GITHUB_ENV
          echo "APP_IOS_PASSWORD=${{ secrets.APP_IOS_PASSWORD }}" >> $GITHUB_ENV
          echo "GIT_USER_TOKEN=${{ secrets.GIT_USER_TOKEN }}" >> $GITHUB_ENV
          echo "GIT_USER_EMAIL=${{ secrets.GIT_USER_EMAIL }}" >> $GITHUB_ENV
          echo "APPLE_ID=${{ secrets.APPLE_ID }}" >> $GITHUB_ENV
          echo "ITC_TEAM_ID=${{ secrets.ITC_TEAM_ID }}" >> $GITHUB_ENV
          echo "ITC_TEAM_NAME=${{ secrets.ITC_TEAM_NAME }}" >> $GITHUB_ENV
          echo "APPLE_DEVELOPER_TEAM_ID=${{ secrets.APPLE_DEVELOPER_TEAM_ID }}" >> $GITHUB_ENV
          echo "APP_VERSION_CODE=${{ needs.initialize.outputs.VERSION_CODE  }}" >> $GITHUB_ENV
          echo "APP_VERSION_NUMBER=${{ needs.initialize.outputs.VERSION_NUMBER }}" >> $GITHUB_ENV
          echo "APP_IOS_VERSION_NUMBER=${{ needs.initialize.outputs.IOS_VERSION }}" >> $GITHUB_ENV

      - name: Download bundle dependencies
        run: |
          gem install bundler:2.0.2
          bundle config path vendor/bundle
          bundle install
        working-directory: ios/app/fastlane

      - name: Build and deploy
        run: |
          echo "LC_ALL=fr_FR.UTF-8" >> $GITHUB_ENV
          echo "LANG=fr_FR.UTF-8" >> $GITHUB_ENV
          bundle exec fastlane ${{ needs.initialize.outputs.DEPLOY_TYPE }} 
        working-directory: ios/app/fastlane

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v3
        with:
          name: iOS App - ${{ needs.initialize.outputs.VERSION_NUMBER }} - IPA
          path: ${{ env.IPA_LOCATION }}
          retention-days: 3

      - name: Upload DSYM Artifact
        uses: actions/upload-artifact@v3
        with:
          name: iOS App - ${{ needs.initialize.outputs.VERSION_NUMBER }} - DSYM
          path: ${{ env.DSYM_LOCATION }}
          retention-days: 3

      - name: Upload XCODE ARCHIVE Artifact
        uses: actions/upload-artifact@v3
        with:
          name: iOS App - ${{ needs.initialize.outputs.VERSION_NUMBER }} - XCODE ARCHIVE
          path: ${{ env.XCODEBUILD_ARCHIVE }}
          retention-days: 3
  

  summary_and_release:
    if: ${{ inputs.deploy_type != 'alpha' }}
    needs: [initialize, deploy_android, deploy_ios]
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download Android Artifact for Github Release
        uses: actions/download-artifact@v3
        id: download_apk
        with:
          name: Android App - ${{ needs.initialize.outputs.VERSION_NUMBER }} - APK

      - name: Download iOS Artifact for Github Release
        uses: actions/download-artifact@v3
        id: download_ipa
        with:
          name: iOS App - ${{ needs.initialize.outputs.VERSION_NUMBER }} - IPA
      
      - name: Push to Github release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            ${{ steps.download_apk.outputs.download_path }}/*.apk
            ${{ steps.download_ipa.outputs.download_path }}/*.ipa
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.initialize.outputs.VERSION_NUMBER }}
          name: Papillon - ${{ needs.initialize.outputs.VERSION_NUMBER }}
          draft: false
          generateReleaseNotes: true
          prerelease: ${{ needs.initialize.outputs.DEPLOY_TYPE == 'beta' }}
          makeLatest: ${{ needs.initialize.outputs.DEPLOY_TYPE == 'prod' }}
          body: |
            **Release de version ${{ needs.initialize.outputs.VERSION_NUMBER }}**
            - [Android] Version **${{ needs.initialize.outputs.VERSION_NUMBER }}**
            - [iOS] Version **${{ needs.initialize.outputs.IOS_VERSION }}**
            - Build  **${{ needs.initialize.outputs.VERSION_CODE }}**

      - name: Deploy summary
        run: |
          echo "### Résumé de déploiement :rocket:" >> $GITHUB_STEP_SUMMARY
          if [ "${{ needs.initialize.outputs.DEPLOY_TYPE }}" == "beta" ]; then
            echo "#### En beta :construction:" >> $GITHUB_STEP_SUMMARY
          else
            echo "#### En production :green_heart:" >> $GITHUB_STEP_SUMMARY
          fi
          echo "Date de déploiement : $(date)" >> $GITHUB_STEP_SUMMARY
          echo "Lien de la release sur GitHub : ${{ steps.create_release.outputs.html_url }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "#### Android :robot:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Version : ${{ needs.initialize.outputs.VERSION_NUMBER }}" >> $GITHUB_STEP_SUMMARY
          echo "Code de version : ${{ needs.initialize.outputs.VERSION_CODE }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "#### iOS :apple:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Version : ${{ needs.initialize.outputs.VERSION_NUMBER }}" >> $GITHUB_STEP_SUMMARY
          echo "Code de version : ${{ needs.initialize.outputs.VERSION_CODE }}" >> $GITHUB_STEP_SUMMARY
          if [ "${{ needs.initialize.outputs.DEPLOY_TYPE }}" == "beta" ]; then
            echo "Déployé sur TestFlight" >> $GITHUB_STEP_SUMMARY
          else
            echo "Déployé sur l'AppStore" >> $GITHUB_STEP_SUMMARY
          fi
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "---" >> $GITHUB_STEP_SUMMARY
          echo "Fin de rapport de déploiement" >> $GITHUB_STEP_SUMMARY
          echo "(c) 2023 - PapillonApp" >> $GITHUB_STEP_SUMMARY

  deploy_alpha:
    if: ${{ inputs.deploy_type == 'alpha' }}
    needs: initialize
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Java
        run: |
          brew tap AdoptOpenJDK/openjdk
          brew install --cask adoptopenjdk15

          echo "JAVA_HOME=$(/usr/libexec/java_home -v 15)" >> $GITHUB_ENV
          echo ${{ env.JAVA_HOME }}
          java -version

      - name: Setup Android CLI
        run: |
          brew install --cask android-commandlinetools
          sdkmanager --update
          set +o pipefail

          yes | sdkmanager --licenses
          yes | sdkmanager --install "platform-tools"
          yes | sdkmanager --install "build-tools;33.0.1"
          yes | sdkmanager --install "platforms;android-33"

          sdkmanager --list_installed
          set -o pipefail

      - name: Setup Android Builder
        run: |
          echo "ANDROID_HOME=$(brew --prefix)/share/android-commandlinetools" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$(brew --prefix)/share/android-commandlinetools" >> $GITHUB_ENV
          echo "APP_VERSION_CODE=${{ needs.initialize.outputs.VERSION_CODE  }}" >> $GITHUB_ENV
          echo "APP_VERSION_NUMBER=${{ needs.initialize.outputs.VERSION_NUMBER }}" >> $GITHUB_ENV
          chmod +x ./android/gradlew;

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Setup dependencies
        run: |
          npm i -g @ionic/cli
          npm i --prefer-offline --no-audit

      - name: Update release canal
        uses: maxgfr/github-change-json@main
        with:
          path: "package.json"
          key: "canal"
          value: ${{ needs.initialize.outputs.DEPLOY_TYPE }}

      - name: Update version number
        uses: maxgfr/github-change-json@main
        with:
          path: "package.json"
          key: "version"
          value: ${{ needs.initialize.outputs.VERSION_NUMBER }}

      - name: Ionic Capacitor Sync
        run: |
          ionic capacitor sync android --prod
     
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true

      - name: Cache bundle dependencies
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-

      - name: Decrypt Android keys
        run: sh ./.github/scripts/decrypt_android_keys.sh
        env:
          KEYS_SECRET_PASSPHRASE: ${{ secrets.KEYS_SECRET_PASSPHRASE }}  

      - name: Export Data to Fastlane
        run: |
          echo "KEY_STORE=$GITHUB_WORKSPACE/android/fastlane/logi12-prnplus.jks" >> $GITHUB_ENV
          echo "KEY_STORE_PASSWORD=${{ secrets.KEY_STORE_PASSWORD}}" >> $GITHUB_ENV
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV
          echo "PLAY_CREDENTIALS_JSON=$GITHUB_WORKSPACE/android/fastlane/play_store.json" >> $GITHUB_ENV
          echo "GRADLE_FILE=$GITHUB_WORKSPACE/android/app/build.gradle" >> $GITHUB_ENV

      - name: Download bundle dependencies
        run: |
          gem install bundler:2.0.2
          bundle config path vendor/bundle
          bundle install
          bundle exec gem install "fastlane-plugin-versioning_android"
        working-directory: android/fastlane

      - name: Build and deploy
        run: |
          echo "LC_ALL=fr_FR.UTF-8" >> $GITHUB_ENV
          echo "LANG=fr_FR.UTF-8" >> $GITHUB_ENV
          bundle exec fastlane alpha
        working-directory: android/fastlane